---
- hosts: web_servers
  become: true
  tasks:
    - name: Update repo and Install nginx
      apt:
        name: "nginx"
        state: present
        update_cache: yes

    - name: Create folder for website
      file:
        path: "/var/www/{{ website_name }}"
        state: directory

    - name: Get update for server
      raw: sudo apt-get update

    - name: Create folder for txt file
      file:
        path: "/var/txt/ring_number"
        state: directory
    
    - name: Creating a file with content
      copy:
        dest: "/var/txt/ring_number/ring.txt"
        content: |
          This is page 1
      
    - name: Creating a bash script
      copy:
        dest: "/usr/local/bin/bash_test.sh"
        content: |
          #!/bin/bash
          # Copying the file to the next server
          chmod 600 ~/bash_test.sh
          scp -i test_ssh_key.pem /home/ec2-user/test.txt ec2-user@100.24.27.15:home/ec2/default ./default  

    - name: Delete sites-enable and sites-available files
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "/etc/nginx/sites-enabled/default"
        - "/etc/nginx/sites-available/default"
      notify:
        - Restart nginx

    - name: Add webpage to servers 
      template:
        src: "index.html.tpl"
        dest: "/var/www/{{ website_name }}/index.html"
      notify:
        - Restart nginx

    - name: Configure nginx with new config file
      template:
        src: "default.tpl"
        dest: "/etc/nginx/sites-available/{{ website_name }}"

    - name: Create symlink for config file
      file:
        src: "/etc/nginx/sites-available/{{ website_name }}"
        dest: "/etc/nginx/sites-enabled/{{ website_name }}"
        state: link
      notify:
        - Restart nginx


- hosts: alpha
  become: true
  tasks:
    - name: Creating a file with content
      copy:
        dest: "/var/txt/ring_number/python_increment_script.py"
        content: |
          #!/usr/bin/env python
          # coding: utf-8

          # In[20]:


          #open and read the file after the appending:
          f = open("/var/txt/ring_number/ring.txt", "r") #open file in read mode
          count = f.read() # read data 
          count = int(count) + 1

          f = open("/var/txt/ring_number/ring.txt", "w") # open file in read mode
          f.write(str(count)) # write count to file
          f.close() # close file



          # In[12]:


          type(count)


          # In[ ]:

  handlers:
    - name: Restart nginx
      service:
        name: nginx
        state: restarted


